name: foyer-dev
channels:
  - conda-forge
dependencies:
  - bump2version
  - codecov
  - lark
  - lxml
  - mbuild>=0.17
  - treelib
  - gmso
  - networkx>=2.5
  - openmm
  - parmed>=3.4.3
  - ele
  - openff-toolkit-base >=0.11
  - pip
  - pre-commit
  - pytest
  - pytest-azurepipelines
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - python>=3.10
  - requests
  - requests-mock
